# The GroupBy Object

In [1]:
import pandas as pd

## The Fortune 1000 Dataset
- The **Fortune 1000** is a listing of the 1000 largest American companies as ranked by Fortune magazine.
- The **DataFrame** includes the company's name, sector, industry, and revenues, profits, and employees.

In [22]:
fortune= pd.read_csv("fortune1000.csv",index_col="Rank")

## The groupby Method
- **Grouping** is a way to organize/categorize/group the data based on a column's values.
- The `groupby` method returns a **DataFrameGroupBy** object. It resembles a group/collection of **DataFrames** in a dictionary-like structure.
- The **DataFrameGroupBy** object can perform aggregate operations on *each* group within it.

In [7]:
fortune

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400
...,...,...,...,...,...,...
996,New York Community Bancorp,Financials,Commercial Banks,1902,-47,3448
997,Portland General Electric,Energy,Utilities: Gas and Electric,1898,172,2646
997,Portland General Electric,Energy,Utilities: Gas and Electric,1898,172,2646
999,Wendy’s,"Hotels, Resturants & Leisure",Food Services,1896,161,21200
1000,Briggs & Stratton,Industrials,Industrial Machinery,1895,46,5480

In [23]:
sectors=fortune.groupby("Sector")

In [19]:
sectors.max()

,Company,Industry,Revenue,Profits,Employees
Sector,,,,,
Aerospace & Defense,Woodward,Aerospace and Defense,96114,7608,197200
Apparel,Wolverine World Wide,Apparel,30601,3273,65300
Business Services,Western Union,Waste Management,19330,6328,216500
Chemicals,Westlake Chemical,Chemicals,48778,7685,52000
Energy,Xcel Energy,Utilities: Gas and Electric,246204,16150,75600
Engineering & Construction,Tutor Perini,Homebuilders,18114,803,92000
Financials,Zions Bancorp.,Securities,210821,24442,331000
Food and Drug Stores,Whole Foods Market,Food and Drug Stores,153290,5237,431000
"Food, Beverages & Tobacco",WhiteWave Foods,Tobacco,67702,7351,263000
Health Care,inVentiv Health,Wholesalers: Health Care,181241,18108,203500
"Hotels, Resturants & Leisure",Yum Brands,"Hotels, Casinos, Resorts",25413,5920,505000
Household Products,Vista Outdoor,Miscellaneous,78756,7036,110000
Industrials,Zebra Technologies,Miscellaneous,140389,4833,333000
Materials,Worthington Industries,"Packaging, Containers",22534,991,60000
Media,iHeartMedia,"Publishing, Printing",52465,8382,185000
Motor Vehicles & Parts,Wabash National,Motor Vehicles and Parts,152356,9687,215000
Retailing,hhgregg,Specialty Retailers: Other,482130,14694,2300000
Technology,salesforce.com,Semiconductors and Other Electronic Components,233715,53394,411798
Telecommunications,Windstream Holdings,Telecommunications,146801,17879,281450
Transportation,YRC Worldwide,"Trucking, Truck Leasing",58363,7610,341240
Wholesalers,World Fuel Services,Wholesalers: Food and Grocery,48681,1472,78500

## Retrieve a Group with the get_group Method
- The `get_group` method on the **DataFrameGroupBy** object retrieves a nested **DataFrame** belonging to a specific group/category.

## Methods on the GroupBy Object
- Use square brackets on the **DataFrameGroupBy** object to "extract" a column from the original **DataFrame**.
- The resulting **SeriesGroupBy** object will have aggregation methods available on it.
- Pandas will perform the calculation on *every* group within the collection.
- For example, the `sum` method will sum together the **Revenues** for every row by group/category.

## Grouping by Multiple Columns
- Pass a list of columns to the **groupby** method to group by pairings of values across columns.
- Target a column to retrieve the **SeriesGroupBy** object, then perform an aggregation with a method.
- Pandas will return a **MultiIndex** **Series** where the levels will be the original groups.

In [38]:
fortune.nlargest(2,"Employees")

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
218,Yum Brands,"Hotels, Resturants & Leisure",Food Services,13105,1293,505000

## The agg Method
- The `agg` method applies different aggregation methods on different columns.
- Invoke the `agg` method directly on the **DataFrameGroupBy** object.
- Pass the method a dictionary where the keys are the columns and the values are the aggregation operations.

In [52]:
sectors.apply(func=lambda df:df.nlargest(2,"Revenue"))

                                                    Company  \
Sector                       Rank
Aerospace & Defense          24                      Boeing
                             45         United Technologies
Apparel                      91                        Nike
                             231                         VF
Business Services            144              ManpowerGroup
                             186              Omnicom Group
Chemicals                    56                Dow Chemical
                             101                     DuPont
Energy                       2                  Exxon Mobil
                             14                     Chevron
Engineering & Construction   155                      Fluor
                             156                      AECOM
Financials                   4           Berkshire Hathaway
                             16                  Fannie Mae
Food and Drug Stores         7                   CVS Health
                             17                      Kroger
Food, Beverages & Tobacco    41      Archer Daniels Midland
                             44                     PepsiCo
Health Care                  5                     McKesson
                             6           UnitedHealth Group
Hotels, Resturants & Leisure 109                 McDonald’s
                             146                  Starbucks
Household Products           34            Procter & Gamble
                             151             Kimberly-Clark
Industrials                  11            General Electric
                             59                 Caterpillar
Materials                    126                      Alcoa
                             127        International Paper
Media                        53                      Disney
                             96    Twenty-First Century Fox
Motor Vehicles & Parts       8               General Motors
                             9                   Ford Motor
Retailing                    1                      Walmart
                             15                      Costco
Technology                   3                        Apple
                             18                  Amazon.com
Telecommunications           10                        AT&T
                             13                     Verizon
Transportation               48                         UPS
                             58                       FedEx
Wholesalers                  57                       Sysco
                             64                Ingram Micro

                                                         Sector  \
Sector                       Rank
Aerospace & Defense          24             Aerospace & Defense
                             45             Aerospace & Defense
Apparel                      91                         Apparel
                             231                        Apparel
Business Services            144              Business Services
                             186              Business Services
Chemicals                    56                       Chemicals
                             101                      Chemicals
Energy                       2                           Energy
                             14                          Energy
Engineering & Construction   155     Engineering & Construction
                             156     Engineering & Construction
Financials                   4                       Financials
                             16                      Financials
Food and Drug Stores         7             Food and Drug Stores
                             17            Food and Drug Stores
Food, Beverages & Tobacco    41       Food, Beverages & Tobacco
                             44       Food, Beverages & Tobacco
Health Care                  5                      Health Care
                             6                      Health Care
Hotels, Resturants & Leisure 109   Hotels, Resturants & Leisure
                             146   Hotels, Resturants & Leisure
Household Products           34              Household Products
                             151             Household Products
Industrials                  11                     Industrials
                             59                     Industrials
Materials                    126                      Materials
                             127                      Materials
Media                        53                           Media
                             96                           Media
Motor Vehicles & Parts       8           Motor Vehicles & Parts
                             9           Motor Vehicles & Parts
Retailing                    1                        Retailing
                             15                       Retailing
Technology                   3                       Technology
                             18                      Technology
Telecommunications           10              Telecommunications
                             13              Telecommunications
Transportation               48                  Transportation
                             58                  Transportation
Wholesalers                  57                     Wholesalers
                             64                     Wholesalers

                                                                        Industry  \
Sector                       Rank
Aerospace & Defense          24                            Aerospace and Defense
                             45                            Aerospace and Defense
Apparel                      91                                          Apparel
                             231                                         Apparel
Business Services            144                                  Temporary Help
                             186                          Advertising, marketing
Chemicals                    56                                        Chemicals
                             101                                       Chemicals
Energy                       2                                Petroleum Refining
                             14                               Petroleum Refining
Engineering & Construction   155                       Engineering, Construction
                             156                       Engineering, Construction
Financials                   4          Insurance: Property and Casualty (Stock)
                             16                           Diversified Financials
Food and Drug Stores         7                              Food and Drug Stores
                             17                             Food and Drug Stores
Food, Beverages & Tobacco    41                                  Food Production
                             44                           Food Consumer Products
Health Care                  5                          Wholesalers: Health Care
                             6           Health Care: Insurance and Managed Care
Hotels, Resturants & Leisure 109                                   Food Services
                             146                                   Food Services
Household Products           34                  Household and Personal Products
                             151                 Household and Personal Products
Industrials                  11                             Industrial Machinery
                             59                  Construction and Farm Machinery
Materials                    126                                          Metals
                             127                           Packaging, Containers
Media                        53                                    Entertainment
                             96                                    Entertainment
Motor Vehicles & Parts       8                          Motor Vehicles and Parts
                             9                          Motor Vehicles and Parts
Retailing                    1                             General Merchandisers
                             15                       Specialty Retailers: Other
Technology                   3                       Computers, Office Equipment
                             18                  Internet Services and Retailing
Telecommunications           10                               Telecommunications
                             13                               Telecommunications
Transportation               48              Mail, Package, and Freight Delivery
                             58              Mail, Package, and Freight Delivery
Wholesalers                  57                    Wholesalers: Food and Grocery
                             64    Wholesalers: Electronics and Office Equipment

                                   Revenue  Profits  Employees
Sector                       Rank
Aerospace & Defense          24      96114     5176     161400
                             45      61047     7608     197200
Apparel                      91      30601     3273      62600
                             231     12377     1232      64000
Business Services            144     19330      419      27000
                             186     15134     1094      74900
Chemicals                    56      48778     7685      49495
                             101     27940     1953      52000
Energy                       2      246204    16150      75600
                             14     131118     4587      61500
Engineering & Construction   155     18114      413      38758
                             156     17990     -155      92000
Financials                   4      210821    24083     331000
                             16     110359    10954       7300
Food and Drug Stores         7      153290     5237     199000
                             17     109830     2039     431000
Food, Beverages & Tobacco    41      67702     1849      32300
                             44      63056     5452     263000
Health Care                  5      181241     1476      70400
                             6      157107     5813     200000
Hotels, Resturants & Leisure 109     25413     4529     420000
                             146     19163     2757     238000
Household Products           34      78756     7036     110000
                             151     18591     1013      43000
Industrials                  11     140389    -6126     333000
                             59      47011     2102     112200
Materials                    126     22534     -322      60000
                             127     22365      938      56000
Media                        53      52465     8382     185000
                             96      28987     8306      20500
Motor Vehicles & Parts       8      152356     9687     215000
                             9      149558     7373     199000
Retailing                    1      482130    14694    2300000
                             15     116199     2377     161000
Technology                   3      233715    53394     110000
                             18     107006      596     230800
Telecommunications           10     146801    13345     281450
                             13     131620    17879     177700
Transportation               48      58363     4844     341240
                             58      47453     1050     323035
Wholesalers                  57      48681      687      51700
                             64      43026      215      27700

In [51]:
sectors.agg(revenue=pd.NamedAgg("Revenue",np.product))

                                          revenue
Sector
Aerospace & Defense           3341121054704140288
Apparel                       1780803565882703872
Business Services             5620492334958379008
Chemicals                     2861219657572941824
Energy                                          0
Engineering & Construction    2723841810714591232
Financials                                      0
Food and Drug Stores         -6918596647498661888
Food, Beverages & Tobacco    -9151314442816847872
Health Care                  -9223372036854775808
Hotels, Resturants & Leisure  7462702759159005184
Household Products            3421961660615622656
Industrials                  -2783818649591349248
Materials                     7412924986651836416
Media                        -8584505765513981952
Motor Vehicles & Parts        -840589470588731392
Retailing                    -4611686018427387904
Technology                                      0
Telecommunications            7036696700013969408
Transportation                2541191274115891200
Wholesalers                  -2987252558705197056

In [50]:
import numpy as np

## Iterating through Groups 
- The **DataFrameGroupBy** object supports the `apply` method (just like a **Series** and a **DataFrame** do).
- The `apply` method invokes a function on every nested **DataFrame** in the **DataFrameGroupBy** object.
- It captures the return values of the functions and collects them in a new **DataFrame** (the return value).